# Generated by Django 3.2.9 on 2021-11-29 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['pk']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='complete',
            new_name='is_complete',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='modified',
            new_name='task_start_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_category',
            field=models.CharField(choices=[('Home Task', 'Home Task'), ('Office Task', 'Office Task'), ('MISC', 'Miscellaneous')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
